# Generated by Django 5.2.4 on 2025-07-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Danca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Participante')),
                ('estilo', models.CharField(max_length=100, verbose_name='Estilo de Dança')),
            ],
        ),
        migrations.CreateModel(
            name='GinasticaCerebral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Participante')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoConvivenciaTerapeutica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Integrante')),
                ('tema', models.CharField(max_length=255, verbose_name='Tema Terapêutico')),
            ],
        ),
        migrations.CreateModel(
            name='Pilates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('nivel', models.CharField(max_length=100, verbose_name='Nível')),
            ],
        ),
        migrations.CreateModel(
            name='PinturaEmTecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Participante')),
                ('tecnica', models.CharField(max_length=100, verbose_name='Técnica Utilizada')),
            ],
        ),
        migrations.CreateModel(
            name='TaiChiChuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('grau', models.CharField(max_length=100, verbose_name='Grau')),
            ],
        ),
    ]
