# Generated by Django 5.2.4 on 2025-07-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonecando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('material', models.CharField(max_length=100, verbose_name='Material usado')),
            ],
        ),
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Participante')),
                ('aparelho', models.CharField(max_length=100, verbose_name='Modelo do Aparelho')),
            ],
        ),
        migrations.CreateModel(
            name='Informatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('nivel', models.CharField(max_length=100, verbose_name='Nível de Conhecimento')),
            ],
        ),
        migrations.CreateModel(
            name='Teclado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Aluno')),
                ('experiencia', models.TextField(blank=True, verbose_name='Experiência anterior')),
            ],
        ),
        migrations.CreateModel(
            name='Violao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Aluno')),
                ('horario', models.CharField(max_length=100, verbose_name='Horário')),
                ('turma', models.CharField(max_length=50, verbose_name='Turma')),
            ],
        ),
    ]
