# Generated by Django 5.2.4 on 2025-07-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('endereco_completo', models.TextField(verbose_name='Endereço completo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do compromisso')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora do compromisso')),
            ],
        ),
    ]
