# Generated by Django 5.2.4 on 2025-07-22 16:49

import atividades_fisicas.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DancaSenior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', ckeditor.fields.RichTextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='atividades_fisicas/imagens/')),
                ('imagem1', models.ImageField(blank=True, null=True, upload_to='atividades_fisicas/imagens/')),
                ('imagem2', models.ImageField(blank=True, null=True, upload_to='atividades_fisicas/imagens/')),
                ('imagem3', models.ImageField(blank=True, null=True, upload_to='atividades_fisicas/imagens/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ginastica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', ckeditor.fields.RichTextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='atividades_fisicas/imagens/')),
                ('imagem1', models.ImageField(blank=True, null=True, upload_to='atividades_fisicas/imagens/')),
                ('imagem2', models.ImageField(blank=True, null=True, upload_to='atividades_fisicas/imagens/')),
                ('imagem3', models.ImageField(blank=True, null=True, upload_to='atividades_fisicas/imagens/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=atividades_fisicas.models.imagem_upload_path)),
                ('legenda', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PosturaAlongamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', ckeditor.fields.RichTextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='atividades_fisicas/imagens/')),
                ('imagem1', models.ImageField(blank=True, null=True, upload_to='atividades_fisicas/imagens/')),
                ('imagem2', models.ImageField(blank=True, null=True, upload_to='atividades_fisicas/imagens/')),
                ('imagem3', models.ImageField(blank=True, null=True, upload_to='atividades_fisicas/imagens/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Yoga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', ckeditor.fields.RichTextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='atividades_fisicas/imagens/')),
                ('imagem1', models.ImageField(blank=True, null=True, upload_to='atividades_fisicas/imagens/')),
                ('imagem2', models.ImageField(blank=True, null=True, upload_to='atividades_fisicas/imagens/')),
                ('imagem3', models.ImageField(blank=True, null=True, upload_to='atividades_fisicas/imagens/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
