# Generated by Django 5.2.4 on 2025-07-23 14:03

import atividades_fisicas.models
import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades_fisicas', '0002_dancasenior_quem_atualizou_dancasenior_valor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='imagem',
            new_name='arquivo',
        ),
        migrations.AddField(
            model_name='imagem',
            name='descricao',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='dancasenior',
            name='descricao',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dancasenior',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=atividades_fisicas.models.imagem_upload_path),
        ),
        migrations.AlterField(
            model_name='dancasenior',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to=atividades_fisicas.models.imagem_upload_path),
        ),
        migrations.AlterField(
            model_name='dancasenior',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to=atividades_fisicas.models.imagem_upload_path),
        ),
        migrations.AlterField(
            model_name='dancasenior',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to=atividades_fisicas.models.imagem_upload_path),
        ),
        migrations.AlterField(
            model_name='ginastica',
            name='descricao',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ginastica',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=atividades_fisicas.models.imagem_upload_path),
        ),
        migrations.AlterField(
            model_name='ginastica',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to=atividades_fisicas.models.imagem_upload_path),
        ),
        migrations.AlterField(
            model_name='ginastica',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to=atividades_fisicas.models.imagem_upload_path),
        ),
        migrations.AlterField(
            model_name='ginastica',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to=atividades_fisicas.models.imagem_upload_path),
        ),
        migrations.AlterField(
            model_name='posturaalongamento',
            name='descricao',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='posturaalongamento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=atividades_fisicas.models.imagem_upload_path),
        ),
        migrations.AlterField(
            model_name='posturaalongamento',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to=atividades_fisicas.models.imagem_upload_path),
        ),
        migrations.AlterField(
            model_name='posturaalongamento',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to=atividades_fisicas.models.imagem_upload_path),
        ),
        migrations.AlterField(
            model_name='posturaalongamento',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to=atividades_fisicas.models.imagem_upload_path),
        ),
        migrations.AlterField(
            model_name='yoga',
            name='descricao',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='yoga',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=atividades_fisicas.models.imagem_upload_path),
        ),
        migrations.AlterField(
            model_name='yoga',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to=atividades_fisicas.models.imagem_upload_path),
        ),
        migrations.AlterField(
            model_name='yoga',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to=atividades_fisicas.models.imagem_upload_path),
        ),
        migrations.AlterField(
            model_name='yoga',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to=atividades_fisicas.models.imagem_upload_path),
        ),
    ]
